### ISSUE TITLE
Macro deck recent update 

### ISSUE THREAD

**Issue by tismofied** [PhoenixWyllow/Soundboard4MacroDeck2#45] opened 2024-02-09 23:13 UTC
**Describe the bug**
I believe the recent Macro Deck update might have broken the plugin a little.
I am unable to choose audio files from the browse button because said button never shows up 

Macro Deck version 2.13.0
Soundboard4MacroDeck2 version 2.0.2

**Comment by PhoenixWyllow** [comment] 2024-02-10 00:10
The functionality and the screens have been revamped in soundboard v2
Audio files are now added through the configuration screen. See [Readme - Audio File Storage](https://github.com/PhoenixWyllow/Soundboard4MacroDeck2/blob/c081b9eb2117d72dcd21e234099dd4aee7eab305/README.md#audio-file-storage)
There is also a `+` icon in the action configuration screen which gives the same functionality as before but redirected to the new system. 

I did this due to the possibility of adding the same audio file to more than one button (add the file once, play it from multiple buttons), also to allow for playing by category as requested in #35

**Comment by tismofied** [comment] 2024-02-10 00:33
I keep getting this error after I updated Macro Deck. I uninstalled the plugin and installed it  back .
![Untitled](https://github.com/PhoenixWyllow/Soundboard4MacroDeck2/assets/90809124/bc2647a2-ca2c-443a-9681-b46b7105637f)

**Comment by PhoenixWyllow** [comment] 2024-02-10 14:43
could you upload the log file? and also the soundboard.db file found in `%APPDATA%\Macro Deck\plugins\PhoenixWyllow.Soundboard4MacroDeck\DB\`

This is an old issue I fixed before releasing 2.0.0 but there may be an edge case that I didn't cover

**Comment by PhoenixWyllow** [comment] 2024-02-15 17:39
any news? I can't fix this without the files - I cannot reproduce the issue on my pc.

**Comment by tismofied** [comment] 2024-02-15 20:45
Oh man, I have no idea why I didn't get the reply above about the log files. I restored a backup I had made and it's working right now. I don't know what initially happened that gave me that error. 
Sorry again for not replying ro this sooner.

**Comment by PhoenixWyllow** [comment] 2024-02-15 20:49
don't sweat it :) it's easy to miss the notifications
glad it's working now! I'll go ahead and close this issue.

**Closed by PhoenixWyllow** 2024-02-15 20:49 UTC
